In [18]:
import numpy as np

A = np.random.rand(3,3)

def LU(A):
    L = np.zeros(A.shape, float)
    U = np.zeros(A.shape, float)
    temp = np.copy(A)
    for i in range(len(A)): # 0 1 2
        L[:, i]   = temp[:, i]/temp[i,i]
        U[i, :] = temp[i, :]
        temp -= np.dot((L[:, i]).reshape(len(A),1), (U[i, :]).reshape(1, len(A)))
    return L, U

L, U  = LU(A)

print("L: ")
print(L, '\n')
print("U: ")
print(U, '\n')
print("Distance: ", np.linalg.norm(np.dot(L,U)-A))



L: 
[[ 1.         -0.         -0.        ]
 [10.95304711  1.         -0.        ]
 [ 0.24336893 -0.85863308  1.        ]] 

U: 
[[ 0.05313663  0.11427759  0.88031903]
 [ 0.         -1.10745251 -9.37923597]
 [ 0.          0.         -8.16805463]] 

Distance:  1.4895204919483639e-15
